/* Author: Raz#7970 */
function customtheme () {
injecttheme("CTH", "* { --background-primary: 30,30,30; --background-secondary: 20,20,20; --background-secondary-alt: 15,15,15; --background-accent: 50,50,50; --background-floating: #28242bbf; --scrollbar-thin-track: #00000000; --channeltextarea-background: #151515 }") 
injecttheme("CTH", ".theme-dark .container-2cd8Mz { background-color: #cecece00 }") 
injecttheme("CTH", ".theme-dark { --interactive-hover: #5682af; --text-normal: #778a88; --header-secondary: #185cc3 }") 
injecttheme("CTH", ".scroller-18M1mG { padding-bottom: 2px; background-color: #00000069; color: #00000069 }") 
injecttheme("CTH", ".theme-dark .selected-3H3-RC { background-color: #0102044f }") 
injecttheme("CTH", ".ownerIcon-255uKo { color: blue; margin-left: 4px }") 
injecttheme("CTH", ".attachButtonPlay-1ATmb5 { color: hsl(139,calc(var(--saturation-factor, 1)*47.3%),43.9%) }") 
injecttheme("CTH", ".pencilIcon-z04-c5 { color: #00b8ff }") 
injecttheme("CTH", ".icon-2xnN2Y { color: #154baa }") 
injecttheme("CTH", ".icon-Lupfh- { color: blue }") 
injecttheme("CTH", ".buttonWrapper-3YFQGJ { color: #a988a947 }") 
injecttheme("CTH", ".homeIcon-r0w4ny { color: deepskyblue }") 
injecttheme("CTH", ".wrapper-3kah-n.selected-1Drb7Z .childWrapper-1j_1ub, .wrapper-3kah-n:hover .childWrapper-1j_1ub { color: #09054987; background-color: #025773 }") 
injecttheme("CTH", ".linkButtonIcon-7rsZcu { color: #fa23fa }") 
injecttheme("CTH", ".applicationStore-2nk7Lo { background-color: #cecece00 }") 
injecttheme("CTH", ".clickable-ZD7xvu .icon-2xnN2Y { color: #205db9 }") 
injecttheme("CTH", ".item-3XjbnG { background-color: #0606082e }") 
injecttheme("CTH", ".brand-3g5E0C.item-3XjbnG, .themed-2-lozF.item-3XjbnG { color: #125fd3; background-color: rgb(0 0 0 / 0%) }") 
injecttheme("CTH", ".theme-dark .root-g14mjS { background-color: rgb(0 0 0 / 0%) }") 
injecttheme("CTH", ".winButton-3UMjdg { color: #0066ff }") 
injecttheme("CTH", ".attachButtonPlus-3IYelE { color:dodgerblue }") 
injecttheme("CTH", ".app-2CXKsg button { color: dodgerblue }") 
injecttheme("CTH", ".wordmarkWindows-2dq6rw { color: #1266f8 }") 
injecttheme("CTH", ".flowerStar-2tNFCR { width: 100%; height: 100%; color: slateblue }") 
injecttheme("CTH", ".theme-dark .footer-31IekZ { background-color: #00000000 }") 
injecttheme("CTH", ".theme-dark .message-G6O-Wv { background-color: #54638126 }") 
injecttheme("CTH", ".newMessagesBar-1hF-9G { background-color: #202 }") 
injecttheme("CTH", ".divider-2rZFJK { align-items: end }") 
injecttheme("CTH", ".colorStandard-21JIj7 { color: rgb(28 69 182) }") 
injecttheme("CTH", ".title-2dsDLn { color: #00dcff }") 
}
